sudo: false
language: node_js
node_js:
- 12
os: linux
dist: trusty
branches:
  only:
  - master
deploy:
  provider: heroku
  strategy: api
  app: made-up-world-reactjs
  on:
    repo: mrWD/made-up-world-reactjs
  api_key:
    secure: 75209df3-e134-4f96-ac6d-11b540d5952d
