language: node_js
node_js:
- 12
os: linux
dist: trusty
branches:
  only:
  - master
deploy:
  provider: heroku
  strategy: api
  app: made-up-world-reactjs
  on:
    repo: mrWD/made-up-world-reactjs
  api_key:
    secure: hrnwiNVdoJtpTVt0Pb9frko5BazI0TyMB5D7ZSfjS5Cn9D9iKXqV7Pry+9GSdyJaKH+5koY+DKyDmHbYh73HXCopIxUZ+cCPlDpEvICqKlSgo0kcMfKo4yBpXT6GWFTLN69gepI1eExMz0/IPpIp8cLZ7ljS3aksPif2N67/48oaVZA7/Fy+mF7UaSb/99PPblPCmlNj4c7qDRBmCmTeA//O0+BRS6yuQA1/29REjdzlkqkP5UYUpG644R85Zi5/XXzbZYLYjxG3zjtWnWxdMOLiqxnsKccRiM86yHOHh2qHxNVUjCn7SUnZoDfCbat8ckxsj8s5kMX12cJGvBr+89VuDH9R7DHUb6/2osmuSuAovPqB8yoWhE9wJ88iPyqLVyqObbcRDc66qH9gnxAYy5L032HdsGFv/mfLbq592u+lo6zDGjxAAX5fNMkRsdVqJl9NnSwLNpGwosloZvjLgz4/j7DGPhTTp99bNVvCYByk+m8JjISHVixXLiOVT5BjkpP99SdazE1+y8N313plLmHj8D2Sf/sszo+hWQeB8f++aXKETxJiqAgZMmdTV3DMjkk/buOrfKm4vtnz1xp6YTQcHdb/t3eJR7AMVItR1MJ0aAbIguX+4L/mP7S8ch3qIOPt7+8fbdBu0w7JeI83m8K21MaaraDhdnbogOccTBo=
